### ISSUE TITLE
Harden `py-ssz` to adversarial inputs

### ISSUE THREAD

**Issue by ralexstokes** [ethereum/py-ssz#108]
reported by Mehdi wrt the beacon fuzz efforts run by Sigma Prime:

e.g.

```python
import ssz
ssz.encode(True, "byte")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/scop/.local/lib/python3.6/site-packages/ssz/codec.py", line 28, in encode
    return sedes_obj.serialize(value)
  File "/home/scop/.local/lib/python3.6/site-packages/ssz/sedes/byte.py", line 14, in serialize
    if len(value) != 1:
TypeError: object of type 'bool' has no len()
```

```python
import ssz
ssz.encode('', 'uint32')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/scop/.local/lib/python3.6/site-packages/ssz/codec.py", line 28, in encode
    return sedes_obj.serialize(value)
  File "/home/scop/.local/lib/python3.6/site-packages/ssz/sedes/uint.py", line 15, in serialize
    if value < 0:
TypeError: '<' not supported between instances of 'str' and 'int'
```

**Comment by ralexstokes** [comment]
after some internal conversation, we decided to put this responsibility on the programmer to use `encode` correctly

**Comment by pipermerriam** [comment]
Is there a reason not to do some basic type checking and raise friendlier errors?

**Comment by ralexstokes** [comment]
not really, but then this becomes a slightly different issue (as it was motivated by fuzzing efforts), i'll re-open and change the title to reflect this is more about usability
